import 'package:bookbuffet/controller/bottom_bar.dart';
import 'package:bookbuffet/main.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pbp_django_auth/pbp_django_auth.dart';
import 'package:bookbuffet/pages/base.dart';
import 'package:provider/provider.dart';
import 'dart:async';
import 'dart:convert';
